# site settings
title: robkorv.nl
author: Robbert Korving
email: r.korving@gmail.com
description: >
  Dit is het kladblok van Robbert Korving, ik plaats hier aantekeningen voor
  open-source ontwikkel avonturen.
baseurl: ""
url: "https://robkorv.nl"
twitter_username: robkorv
github_username:  robkorv
production: true

# render settings
markdown: kramdown
kramdown:
  enable_coderay: false
highlighter: rouge

# output settings
permalink: /:title
sass:
    style: :compressed

# do not render
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE
